#!/bin/bash
# module load gcc/10.2.0-zuvaafu  # update gcc and gcov (gcov (GCC) 4.8.5 by default)

src="$1"
src_name="$(basename $src)"
exe_input="$2"

[ -f $src ] || (echo "$src does not exist" && exit 1)
[ -f $exe_input ] || (echo "$exe_input does not exist" && exit 1)

$(dirname $0)/gcov_clean $src_name || exit 2

exe="instrumented_exes/$(basename ${src%.*})"
mkdir -p instrumented_exes
echo "$src -> $exe"
case "$src_name" in
    *.c)   CC="gcc" ;;
    *.cpp) CC="g++" ;;
esac
$CC --coverage $src -o $exe || exit 3

./$exe < $exe_input > $src_name.gcov.output
echo $? >> $src_name.gcov.exitcode

gcov -b -c -i $src_name > $src_name.gcov.report || exit 4
gunzip -c $src_name.gcov.json.gz > $src_name.gcov.json || exit 4

ls *.gc*